### ISSUE TITLE
En ejercicios como 'un saludo superior', hay un warning si usamos identificadores cortos...

### ISSUE THREAD

**Issue by geh** [pdep-utn/mumuki-guia-funcional-aplicacion-parcial-y-orden-superior#1]
... pero el ejercicio pide definir una función cuyo nombre es 'sr'. Entonces no se puede tener el ejercicio en verde.

**Comment by flbulgarelli** [comment]
Hola @geh!

Resuelto. La funcionalidad de detección de identificadores cortos es nueva, y puede haber contenido que no haya sido actualizado apropiadamente.

En concreto, la inspección se llama `HasTooShortIdentifiers`; si encontrás ejercicios que en su enunciado piden funciones que tienen menos de 3 caracteres y fallan, en la biblioteca agregá en la sección de expectativas lo siguiente al ejercicio en cuestión: 

```
* Except:HasTooShortIdentifiers
```

De esa forma el warning desaparecerá.  Mirá por ejemplo https://bibliotheca.mumuki.io/#/guides/pdep-utn/mumuki-guia-funcional-aplicacion-parcial-y-orden-superior/exercises/7.
